package com.vroom.chart

import com.facebook.proguard.annotations.DoNotStrip
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.BindingsInstallerHolder
import com.facebook.react.turbomodule.core.interfaces.TurboModuleWithJSIBindings

// TurboModule counterpart to ../../ios/VroomChartModule.mm. TurboModuleManager
// calls getBindingsInstaller() when it instantiates this module and runs the
// returned installer against the JSI runtime, which exposes
// `global.VroomChartJSI` via the same platform-agnostic vroom::installJsi()
// the iOS module calls. Implemented in ../../cpp/VroomChartJsiBindings.cpp and
// bound by ../../cpp/OnLoad.cpp.
//
// `NativeVroomChartSpec` is generated by React Native's codegen from
// ../../../src/NativeVroomChart.ts (codegenConfig.android.javaPackageName in
// package.json) — the same class name iOS's codegen generates.
@ReactModule(name = NativeVroomChartSpec.NAME)
class VroomChartModule(reactContext: ReactApplicationContext) :
    NativeVroomChartSpec(reactContext), TurboModuleWithJSIBindings {

  companion object {
    init {
      System.loadLibrary("vroomchart")
    }
  }

  @DoNotStrip external override fun getBindingsInstaller(): BindingsInstallerHolder

  // Reaching this module from JS means TurboModuleManager already ran the
  // installer above. JS verifies global.VroomChartJSI itself rather than
  // trusting this return value — see ../../../src/useChartCore.ts.
  override fun install(): Boolean = true
}
