package com.vroom.chart

import com.facebook.jni.HybridData
import com.facebook.proguard.annotations.DoNotStrip
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.BindingsInstallerHolder
import com.facebook.react.turbomodule.core.interfaces.TurboModuleWithJSIBindings

// TurboModule counterpart to ../../ios/VroomChartModule.mm. In RN 0.85+
// bridgeless mode, JSI bindings are installed via TurboModuleWithJSIBindings
// interface — the runtime is passed directly by the TurboModule infrastructure
// rather than being fetched from javaScriptContextHolder.
//
// `NativeVroomChartSpec` is generated by React Native's codegen from
// ../../../src/NativeVroomChart.ts (codegenConfig.android.javaPackageName in
// package.json) — the same class name iOS's codegen generates.
@ReactModule(name = NativeVroomChartSpec.NAME)
class VroomChartModule(reactContext: ReactApplicationContext) :
    NativeVroomChartSpec(reactContext),
    TurboModuleWithJSIBindings {

  companion object {
    init {
      System.loadLibrary("vroomchart")
    }
  }

  @Volatile
  private var installed = false

  // Legacy JNI entry point for bridge-based installation (fallback)
  private external fun nativeInstall(runtimePointer: Long): Boolean

  // Creates the BindingsInstallerHolder that the TurboModule infrastructure
  // will invoke with the jsi::Runtime in bridgeless mode.
  @DoNotStrip
  private external fun nativeCreateBindingsInstaller(): HybridData

  @DoNotStrip
  override fun getBindingsInstaller(): BindingsInstallerHolder {
    return BindingsInstallerHolder(nativeCreateBindingsInstaller())
  }

  // Called from native after installBindings completes
  @DoNotStrip
  @Suppress("unused")
  fun markInstalled() {
    installed = true
  }

  override fun install(): Boolean {
    // In new arch with TurboModuleWithJSIBindings, installation happens via
    // getBindingsInstaller(). This method is called from JS after bindings
    // are already installed.
    if (installed) return true

    // Fallback: try direct installation for legacy bridge mode
    val runtimePointer = runCatching {
      reactApplicationContext.javaScriptContextHolder?.get()
    }.getOrNull() ?: return false

    if (runtimePointer == 0L) return false

    installed = nativeInstall(runtimePointer)
    return installed
  }
}
