package com.vroom.chart

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule

// TurboModule counterpart to ../../ios/VroomChartModule.mm. `install()` hands
// the JSI runtime pointer to the native `vroomchart` library (see
// ../../CMakeLists.txt), which installs `global.VroomChartJSI` via the same
// platform-agnostic vroom::installJsi() the iOS bridge calls.
//
// `NativeVroomChartSpec` is generated by React Native's codegen from
// ../../../src/NativeVroomChart.ts (codegenConfig.android.javaPackageName in
// package.json) — the same class name iOS's codegen generates.
@ReactModule(name = NativeVroomChartSpec.NAME)
class VroomChartModule(reactContext: ReactApplicationContext) :
    NativeVroomChartSpec(reactContext) {

  companion object {
    init {
      System.loadLibrary("vroomchart")
    }
  }

  private external fun nativeInstall(runtimePointer: Long): Boolean

  override fun install(): Boolean {
    val runtimePointer =
        reactApplicationContext.javaScriptContextHolder?.get() ?: return false
    return nativeInstall(runtimePointer)
  }
}
